### ISSUE TITLE
uninitialized constant NestedForm::BuilderMixin

### ISSUE THREAD

**Issue by gaaady** [railsadminteam/rails_admin#887]
I just installed rails_admin on Rails 3.1.2 and got the attached exceptions.
I'm using the gem "nested_form"

Any idea what can it be ?

app/views/rails_admin/main/new.html.haml where line #1 raised:

uninitialized constant NestedForm::BuilderMixin

Extracted source (around line #1):

1: = rails_admin_form_for @object, :url => create_path(:model_name => @abstract_model.to_param, :id => @object.id), :html => { :multipart => true, :data => { :title => @page_name } } do |form|
2:   = form.generate :action => :create

---

/app/views/rails_admin/main/new.html.haml where line #1 raised:

valid? is defined by ActiveRecord

Extracted source (around line #1):

1: = rails_admin_form_for @object, :url => create_path(:model_name => @abstract_model.to_param, :id => @object.id), :html => { :multipart => true, :data => { :title => @page_name } } do |form|
2:   = form.generate :action => :create

**Comment by smtlaissezfaire** [comment]
FYI I ran into this while running a production console.  I fixed it by stuffing some requires at the top of my rails admin initializer:

```
require "nested_form/engine"
require "nested_form/builder_mixin"

RailsAdmin.config do |config|
  # ...
end
```

**Comment by fnicastri** [comment]
@sferik 
Issue is back for Rails 6.1.
@smtlaissezfaire fix still works.
With rails 6 everything was ok
